# Makefile for dotfiles

INSTALLATION_DIR := $(HOME)
RENAME_TARGET = $(patsubst dot.%,$(INSTALLATION_DIR)/.%,$(1))
TARGETS_STATIC = $(filter dot.%,$(all_files_in_repos))




include ../mduem/Makefile

# __END__
