#!/bin/bash

vim -u NONE -N -e -s <<END 2>&1 | sed "s|$(pwd)||g"
  let &runtimepath = fnamemodify('vim/dot.vim', ':p')
  source test/libtest.vim
  runtime! $2
  1 verbose source $1
  qall!
END

# __END__
