# Makefile for sh

INSTALLATION_DIR := $(HOME)
RENAME_TARGET = $(patsubst dot.%,$(INSTALLATION_DIR)/.%,$(1))
TARGETS_STATIC = $(filter-out Makefile,$(all_files_in_repos))




include ../mduem/Makefile

# __END__
