# Makefile for opera

# NB: Use a symbolic link to avoid paths with spaces,
# because make(1) cannot treat such paths correctly.
INSTALLATION_DIR := ./profile-link
TARGETS_STATIC = $(filter-out Makefile profile-link,$(all_files_in_repos))




include ../mduem/Makefile

# __END__
